name: banned_words_checker
description: "A powerful and user-friendly banned words checker app designed to help you ensure your content remains clean and appropriate. The app scans text for prohibited words and phrases, providing instant feedback and suggestions for replacements. Ideal for educators, content creators, moderators, and anyone who needs to maintain high standards of language in their communications."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  i18n_extension: ^11.0.12
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.1.14
  http: any
  firebase_core: any
  cloud_firestore: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
