// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD73VGBzGUw9BcvURfDa3TuCBhBBcmPWEQ',
    appId: '1:1036953316945:web:c78d6ef954df3c81885270',
    messagingSenderId: '1036953316945',
    projectId: 'banned-words-checker',
    authDomain: 'banned-words-checker.firebaseapp.com',
    storageBucket: 'banned-words-checker.appspot.com',
    measurementId: 'G-677QYDMYTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUa092knqtoto9kMx3Low8NrFC7kEQuI',
    appId: '1:1036953316945:android:c6e387976f9e2b20885270',
    messagingSenderId: '1036953316945',
    projectId: 'banned-words-checker',
    storageBucket: 'banned-words-checker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9rZpCUY4KHCUpL6u-OvmlwXnt0KyCCs',
    appId: '1:1036953316945:ios:b8cf8ae2e142d664885270',
    messagingSenderId: '1036953316945',
    projectId: 'banned-words-checker',
    storageBucket: 'banned-words-checker.appspot.com',
    iosBundleId: 'com.zeroboy.bannedWordsChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc9rZpCUY4KHCUpL6u-OvmlwXnt0KyCCs',
    appId: '1:1036953316945:ios:b8cf8ae2e142d664885270',
    messagingSenderId: '1036953316945',
    projectId: 'banned-words-checker',
    storageBucket: 'banned-words-checker.appspot.com',
    iosBundleId: 'com.zeroboy.bannedWordsChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD73VGBzGUw9BcvURfDa3TuCBhBBcmPWEQ',
    appId: '1:1036953316945:web:fa79ef285ef21b01885270',
    messagingSenderId: '1036953316945',
    projectId: 'banned-words-checker',
    authDomain: 'banned-words-checker.firebaseapp.com',
    storageBucket: 'banned-words-checker.appspot.com',
    measurementId: 'G-TMZZ2FW3VZ',
  );
}
